# Generated by Django 4.2.13 on 2024-07-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linkedin_url', models.URLField(unique=True)),
                ('is_demo_lead', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('n_employee', models.IntegerField()),
                ('raw_json', models.JSONField()),
                ('company_name_linkedin', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('urn', models.CharField(max_length=200)),
                ('campaign_id', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('urn', models.CharField(max_length=200)),
                ('raw_json', models.JSONField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
